name: 'cargo-semver-checks'
description: 'Ensure the public API in your Rust crate follows semantic versioning'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret, which is necessary to download precompiled binaries from GitHub API. By default, the automatic GitHub token provided to the workflow will be used.'
    required: false
    default: ${{ github.token }}
  package:
    description: 'The package whose API to check for semver (in Package Id Specification format, see https://doc.rust-lang.org/cargo/reference/pkgid-spec.html for reference). If not set, all packages in the workspace are processed.'
    required: false
    default: ''
  manifest-path:
    description: 'Path to Cargo.toml of crate or workspace to check. Has an effect only if package is not specified.'
    required: false
    default: ''
  verbose:
    description: 'Enables verbose output of `cargo-semver-checks`.'
    type: boolean
    required: true
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
