name: 'cargo-semver-checks'
description: 'Ensure the public API in your Rust crate follows semantic versioning'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  crate-name:
    description: 'The crate whose API to check for semver. If not set, all crates in the workspace are processed.'
    required: false
    default: ''
  manifest-path:
    description: 'Path to Cargo.toml of crate or workspace to check. Has an effect only if crate-name is not specified.'
    required: false
    default: ''
  verbose:
    description: 'Enables verbose output of `cargo-semver-checks`.'
    type: boolean
    required: true
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'