name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-action-ubuntu-latest:
    name: Test the action on ubuntu-latest
    uses: ./.github/workflows/test-action.yml
    with:
      runs-on: ubuntu-latest

  test-action-macos-latest:
    name: Test the action on macos-latest
    uses: ./.github/workflows/test-action.yml
    with:
      runs-on: macos-latest
