name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-action-ubuntu-latest:
    uses: ./test-action.yml
    with:
      runs-on: ubuntu-latest

  test-action-windows-latest:
    uses: ./test-action.yml
    with:
      runs-on: windows-latest

  test-action-macos-latest:
    uses: ./test-action.yml
    with:
      runs-on: macos-latest
