name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-build:
    name: Test build
    uses: ./.github/workflows/test-build.yml

  test-action:
    name: Test the action
    uses: ./.github/workflows/test-action.yml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    with:
      runs-on: ${{ matrix.os }}
