name: Test rustdoc caching

on:
  workflow_call:

jobs:
  test-cache-exists:
    name: Check if the cache exists after running the action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the test repository and test with patch change and patch version bump
        uses: actions/checkout@v3
        with:
          path: 'ref_slice'
          repository: mgr0dzicki/cargo-semver-action-ref-slice
          ref: patch_change
      - name: Checkout the action
        uses: actions/checkout@v3
        with:
          path: action
      - name: Run the action
        uses: ./action/
        with:
          manifest-path: 'ref_slice/Cargo.toml'
          cache-key: testkey
          prefix-key: testprefix
      - name: Check if the cache directory exists
        run: |
          if ! grep -q "ref_slice-1.2.1/src/lib.rs" "semver-checks/target/semver-checks/cache/registry-ref_slice-1_2_1.json"; then
            echo "Non-existent or invalid cache file!"
            exit 1
          fi
      - name: Move the cache created by the action
        run: |
          mv semver-checks/target/semver-checks/cache restored-cache
          ls semver-checks/target/semver-checks
      - name: Download saved cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/semver-checks/target/semver-checks/cache
          fail-on-cache-miss: true
          key: test
          restore-keys: |
            testprefix-testkey-linux-rustc-1.68.2-(9eb3afe9e-2023-03-27)-cargo-semver-checks-0.19.0-da39a3ee5e6b4b0d3255bfef95601890afd80709-semver-checks-rustdoc
      - name: Compare local and downloaded cache files
        run: |
          if ! diff -r "semver-checks/target/semver-checks/cache" "restored-cache"; then
            echo "Updated cache does not match the local version!"
            exit 1
          fi
